version: 2

mkdocs:
  configuration: mkdocs.yaml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - curl -fsSL https://pixi.sh/install.sh | bash
      - export PATH="$HOME/.pixi/bin:$PATH"
      - pixi install -e dev

commands:
  - export PATH="$HOME/.pixi/bin:$PATH"
  - pixi run -e dev mkdocs build --config-file mkdocs.yaml --site-dir $READTHEDOCS_OUTPUT/html